[package]
name = "nbt-compress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdeflater = "1.19.0"
zopfli = { version = "0.8.0", features = ["gzip"] }